# Site settings
title: buddhish
description: >- # this means to ignore newlines until "baseurl:"
  Mostly Awake
baseurl: ""  # the subpath of your site, e.g. /blog
#baseurl: "/ipns/escplan.com"  # the subpath of your site, e.g. /blog
url: "https://buddhis.sh" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown
# plugins:
# - jekyll-feed


# Author Info
author:
  name     : sweeper
brand:
  name     : 
  email    :
  github   : 
  twitter  : 
  linkedin : 
  facebook : 

# Posts default Permalink
permalink: /:title

# nostr stuff
include: [".well-known"]

# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
